name: Llamar API y Guardar Resultado

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  api_request:
    runs-on: ubuntu-latest  # Usar un contenedor de Ubuntu para ejecutar el trabajo
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v2  # Extrae el código del repositorio
        
      - name: Llamar a la API
        run: |
          # Hacer la llamada a la API usando curl (puedes usar cualquier otra herramienta como wget)
          curl --request GET \
            --url https://weather-request.p.rapidapi.com/weather/Serbia \
            --header 'x-rapidapi-host: ${{ secrets.API_HOST }}' \
            --header 'x-rapidapi-key: ${{ secrets.API_KEY }}'

      - name: Guardar resultado en un archivo
        run: |
          # Guarda el contenido en un archivo dentro del repositorio
          mv resultado.json ./resultado.json
      
      - name: Subir archivo resultado a GitHub (opcional)
        uses: actions/upload-artifact@v3
        with:
          name: resultado-json
          path: ./resultado.json